### ISSUE TITLE
todo-cli 如何运行起来

### ISSUE THREAD

**Issue by comeCU** [dreamhead/geektime-todo#3]
老师你好，参考[picocli](https://picocli.info/#_running_the_application)运行todo-cli
我碰到了下面的这个报错

```java
E:\idea-workspace\geektime-todo\todo-cli\build\libs> java -cp "picocli-4.6.1.jar;todo-cli-20210807-SNAPSHOT.jar" com.github.dreamhead.todo.cli.Bootstrap
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/dreamhead/todo/core/TodoItemRepository
        at com.github.dreamhead.todo.cli.Bootstrap.main(Bootstrap.java:10)
Caused by: java.lang.ClassNotFoundException: com.github.dreamhead.todo.core.TodoItemRepository
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```

**Comment by dreamhead** [comment]
这个原因是没有把所有的类打包起来，缺少相应的类。我增加了一个打包成一个完整 JAR 包的命令，运行：

```shell
./gradlew uberJar
```

在 todo-cli/build/libs 下就会生成一个 Uber JAR，它是可以独立运行的。

```shell
java -jar todo-uber-<version>.jar
```
```

**Comment by linzehuan** [comment]
java -jar todo-uber-<version>.jar [COMMAND]
